# Generated by Django 3.1.4 on 2021-10-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_offers_button_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
